/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

import { type } from 'os';

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Getting Started',
        },
      ],
    },
        {
      type: 'category',
      label: 'Platform Navigation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Platform Navigation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Building Apps',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Building Apps',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrating with SEMOSS',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Integrating with SEMOSS',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Installation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Advanced Installation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer',
      items: [{
          type: 'category',
          label: 'Reactors',
          link: {
            type: 'generated-index',
            title: 'Reactors',
            description:
              'Documentation for Reactors functionality.',
            slug: '/developer/Reactors',
          },
          items: [
            { type: 'autogenerated', dirName: 'developer/Reactors' }
          ], 
        },
                  {
      type: "category",
      label: "SEMOSS Core API",
      link: {
        type: "generated-index",
        title: "SEMOSS Core API",
        description:
          "This is a sample SEMOSS server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/semoss-core-api"
      },
      items: require("./docs/developer/semoss-core-api/sidebar.ts")
    },
      ],
    },

      {
            type: 'category',
            label: 'Cookbook Recipes',
            link: {
              id: "cookbook/cookbook",
              type: "doc",
            },
            items:[
              {
                type: 'autogenerated',
                dirName: 'Cookbook Recipes',
              }
            ]
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [{ type: 'autogenerated', dirName: 'release-notes' }],
    },
    {
      type: 'category',
      label: 'Client',
      items: [{ type: 'autogenerated', dirName: 'client' }],
    },
  ],

}

export default sidebars;
