apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "semoss-documentation.fullname" . }}-config
  labels:
    {{- include "semoss-documentation.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.env.APP_NAME | quote }}
  MONOLITH_API_URL: {{ .Values.env.MONOLITH_API_URL | quote }}
  SUPPORT_EMAIL: {{ .Values.env.SUPPORT_EMAIL | quote }}
