name: Build Docusaurus documentation

on:
  push:
    branches:
      - main     # or your default branch
  pull_request:  # also build on PRs to catch errors early
  workflow_dispatch:  # allows manual triggering

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.4.1'   # use your project's required version

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      #- name: Install plugin dependencies
      #  run: |
      #    cd packages/docusaurus-plugin-reactor-docgen
      #    pnpm install --frozen-lockfile

      - name: Install dependencies
        run: |
          pnpm install 
      


      - name: Build Docusaurus site
        run: |
          cd docusaurus
          pnpm run build